import puppeteer from 'puppeteer';
const browser = await puppeteer.launch({ headless: 'new', args: ['--no-sandbox'] });
const page = await browser.newPage();
await page.setViewport({ width: 420, height: 900, isMobile: true });
const r = await page.goto('https://n596014.yclients.com', { waitUntil: 'networkidle2', timeout: 60000 });
console.log('status', r.status(), 'url', page.url());
console.log('x-frame-options:', r.headers()['x-frame-options']);
console.log('csp:', r.headers()['content-security-policy']);
await new Promise((x) => setTimeout(x, 5000));
console.log('---TEXT---');
console.log((await page.evaluate(() => document.body.innerText)).slice(0, 1500));
await page.screenshot({ path: 'c:/autosait/koko-studio/yclients.png', fullPage: false });
await browser.close();
